import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/provider/modal-provider";
import { Navbar } from "@/components/navbar/navbar";
import getRules from "@/actions/rule/get.action";
import { Toaster } from "react-hot-toast";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const ruleResponse = await getRules();
  const rules = ruleResponse.rules

  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider 
        //@ts-ignore
          rules={rules}
        />
        <Toaster/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
